import type { Product } from "../../types";

export const mockProducts: Product[] = [
  {
    id: "pizza-margherita",
    vendorId: "vendor-pizza-palace",
    name: "Margherita Pizza",
    description:
      "Classic Italian pizza with fresh mozzarella, tomato sauce, and basil",
    images: [
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop",
    ],
    price: 14.99,
    originalPrice: 17.99,
    category: "pizza",
    cuisine: "Italian",
    isAvailable: true,
    stockCount: 50,
    rating: 4.8,
    reviewCount: 324,
    preparationTime: 15,
    calories: 280,
    ingredients: ["Mozzarella", "Tomato Sauce", "Basil", "Olive Oil"],
    allergens: ["Gluten", "Dairy"],
    customizations: [
      {
        id: "size",
        name: "Size",
        type: "single",
        required: true,
        options: [
          { id: "small", name: 'Small (10")', price: 0 },
          { id: "medium", name: 'Medium (12")', price: 4 },
          { id: "large", name: 'Large (14")', price: 8 },
        ],
      },
      {
        id: "toppings",
        name: "Extra Toppings",
        type: "multiple",
        required: false,
        options: [
          { id: "mushrooms", name: "Mushrooms", price: 2.5 },
          { id: "pepperoni", name: "Pepperoni", price: 2.5 },
          { id: "olives", name: "Olives", price: 2 },
        ],
      },
    ],
  },
  {
    id: "pizza-pepperoni",
    vendorId: "vendor-pizza-palace",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni pizza with mozzarella and tomato sauce",
    images: [
      "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&h=600&fit=crop",
    ],
    price: 16.99,
    category: "pizza",
    cuisine: "Italian",
    isAvailable: true,
    rating: 4.7,
    reviewCount: 512,
    preparationTime: 15,
    calories: 320,
    ingredients: ["Pepperoni", "Mozzarella", "Tomato Sauce"],
    allergens: ["Gluten", "Dairy", "Pork"],
    customizations: [
      {
        id: "size",
        name: "Size",
        type: "single",
        required: true,
        options: [
          { id: "small", name: 'Small (10")', price: 0 },
          { id: "medium", name: 'Medium (12")', price: 4 },
          { id: "large", name: 'Large (14")', price: 8 },
        ],
      },
    ],
  },
  {
    id: "burger-classic",
    vendorId: "vendor-burger-king",
    name: "Classic Burger",
    description: "Beef patty, lettuce, tomato, onion, pickles, special sauce",
    images: [
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&h=600&fit=crop",
    ],
    price: 8.99,
    category: "burgers",
    cuisine: "American",
    isAvailable: true,
    rating: 4.6,
    reviewCount: 892,
    preparationTime: 12,
    calories: 520,
    ingredients: ["Beef Patty", "Lettuce", "Tomato", "Onion", "Pickles"],
    allergens: ["Gluten", "Egg", "Sesame"],
    customizations: [
      {
        id: "cheese",
        name: "Add Cheese",
        type: "single",
        required: false,
        options: [
          { id: "american", name: "American", price: 1 },
          { id: "cheddar", name: "Cheddar", price: 1.5 },
          { id: "swiss", name: "Swiss", price: 1.5 },
        ],
      },
      {
        id: "extras",
        name: "Extras",
        type: "multiple",
        required: false,
        options: [
          { id: "bacon", name: "Bacon", price: 2.5 },
          { id: "egg", name: "Fried Egg", price: 1.5 },
          { id: "avocado", name: "Avocado", price: 2 },
        ],
      },
    ],
  },
  {
    id: "burger-bbq",
    vendorId: "vendor-burger-king",
    name: "BBQ Bacon Burger",
    description: "Beef patty, crispy bacon, onion rings, BBQ sauce",
    images: [
      "https://images.unsplash.com/photo-1553979459-d2229ba7433f?w=800&h=600&fit=crop",
    ],
    price: 12.99,
    category: "burgers",
    cuisine: "American",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 456,
    preparationTime: 15,
    calories: 720,
    ingredients: ["Beef Patty", "Bacon", "Onion Rings", "BBQ Sauce"],
    allergens: ["Gluten", "Egg", "Milk"],
  },
  {
    id: "sushi-philadelphia",
    vendorId: "vendor-sushi-co",
    name: "Philadelphia Roll",
    description: "Salmon, cream cheese, cucumber, avocado",
    images: [
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&h=600&fit=crop",
    ],
    price: 9.99,
    category: "asian",
    cuisine: "Japanese",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 678,
    preparationTime: 10,
    calories: 240,
    ingredients: ["Salmon", "Cream Cheese", "Cucumber", "Avocado", "Rice"],
    allergens: ["Fish", "Gluten", "Dairy"],
  },
  {
    id: "sushi-cali",
    vendorId: "vendor-sushi-co",
    name: "California Roll",
    description: "Crab, avocado, cucumber",
    images: [
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&h=600&fit=crop",
    ],
    price: 7.99,
    category: "asian",
    cuisine: "Japanese",
    isAvailable: true,
    rating: 4.7,
    reviewCount: 892,
    preparationTime: 8,
    calories: 220,
    ingredients: ["Crab", "Avocado", "Cucumber", "Rice"],
    allergens: ["Shellfish", "Gluten"],
  },
  {
    id: "sushi-dragon",
    vendorId: "vendor-sushi-co",
    name: "Dragon Roll",
    description: "Eel, cucumber, avocado, eel sauce",
    images: [
      "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&h=600&fit=crop",
    ],
    price: 14.99,
    category: "asian",
    cuisine: "Japanese",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 523,
    preparationTime: 12,
    calories: 320,
    ingredients: ["Eel", "Cucumber", "Avocado", "Eel Sauce"],
    allergens: ["Fish", "Gluten", "Soy"],
  },
  {
    id: "taco-chicken",
    vendorId: "vendor-taco-bell",
    name: "Chicken Tacos (3 pcs)",
    description: "Grilled chicken, lettuce, tomato, cheese, sour cream",
    images: [
      "https://images.unsplash.com/photo-1565299585323-38174c0a6387?w=800&h=600&fit=crop",
    ],
    price: 8.99,
    category: "mexican",
    cuisine: "Mexican",
    isAvailable: true,
    rating: 4.5,
    reviewCount: 734,
    preparationTime: 10,
    calories: 380,
    ingredients: ["Chicken", "Lettuce", "Tomato", "Cheese", "Sour Cream"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "taco-beef",
    vendorId: "vendor-taco-bell",
    name: "Beef Tacos (3 pcs)",
    description: "Seasoned ground beef, lettuce, tomato, cheese",
    images: [
      "https://images.unsplash.com/photo-1599974579688-8dbdd00bd843?w=800&h=600&fit=crop",
    ],
    price: 8.99,
    category: "mexican",
    cuisine: "Mexican",
    isAvailable: true,
    rating: 4.4,
    reviewCount: 891,
    preparationTime: 10,
    calories: 420,
    ingredients: ["Ground Beef", "Lettuce", "Tomato", "Cheese"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "burrito-chicken",
    vendorId: "vendor-taco-bell",
    name: "Chicken Burrito",
    description:
      "Large flour tortilla with grilled chicken, rice, beans, cheese",
    images: [
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&h=600&fit=crop",
    ],
    price: 9.99,
    category: "mexican",
    cuisine: "Mexican",
    isAvailable: true,
    rating: 4.6,
    reviewCount: 567,
    preparationTime: 12,
    calories: 580,
    ingredients: ["Chicken", "Rice", "Beans", "Cheese", "Tortilla"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "pad-thai",
    vendorId: "vendor-thai-delight",
    name: "Pad Thai",
    description:
      "Stir-fried noodles with shrimp, tofu, peanuts, and tamarind sauce",
    images: [
      "https://images.unsplash.com/photo-1559314809-0d155014bc29?w=800&h=600&fit=crop",
    ],
    price: 13.99,
    category: "asian",
    cuisine: "Thai",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 456,
    preparationTime: 18,
    calories: 520,
    ingredients: ["Rice Noodles", "Shrimp", "Tofu", "Peanuts", "Tamarind"],
    allergens: ["Shellfish", "Peanuts", "Gluten", "Egg", "Soy"],
    customizations: [
      {
        id: "protein",
        name: "Protein",
        type: "single",
        required: false,
        options: [
          { id: "shrimp", name: "Shrimp", price: 0 },
          { id: "chicken", name: "Chicken", price: 2 },
          { id: "tofu", name: "Tofu", price: 0 },
        ],
      },
    ],
  },
  {
    id: "green-curry",
    vendorId: "vendor-thai-delight",
    name: "Green Curry",
    description: "Spicy green curry with chicken, bamboo shoots, and basil",
    images: [
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
    ],
    price: 14.99,
    category: "asian",
    cuisine: "Thai",
    isAvailable: true,
    rating: 4.7,
    reviewCount: 389,
    preparationTime: 20,
    calories: 420,
    ingredients: ["Chicken", "Green Curry", "Bamboo Shoots", "Basil"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "salad-caesar",
    vendorId: "vendor-green-bowl",
    name: "Caesar Salad",
    description: "Crisp romaine, parmesan, croutons, caesar dressing",
    images: [
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop",
    ],
    price: 10.99,
    category: "healthy",
    cuisine: "American",
    isAvailable: true,
    rating: 4.5,
    reviewCount: 234,
    preparationTime: 8,
    calories: 320,
    ingredients: ["Romaine Lettuce", "Parmesan", "Croutons", "Caesar Dressing"],
    allergens: ["Gluten", "Dairy", "Egg"],
  },
  {
    id: "bowl-quinoa",
    vendorId: "vendor-green-bowl",
    name: "Quinoa Power Bowl",
    description:
      "Quinoa, grilled chicken, avocado, black beans, corn, pico de gallo",
    images: [
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
    ],
    price: 12.99,
    category: "healthy",
    cuisine: "Healthy",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 567,
    preparationTime: 15,
    calories: 480,
    ingredients: ["Quinoa", "Chicken", "Avocado", "Black Beans", "Corn"],
    allergens: ["None"],
  },
  {
    id: "dessert-cheesecake",
    vendorId: "vendor-sweet-treats",
    name: "New York Cheesecake",
    description: "Classic creamy cheesecake with berry compote",
    images: [
      "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800&h=600&fit=crop",
    ],
    price: 7.99,
    category: "desserts",
    cuisine: "American",
    isAvailable: true,
    rating: 5.0,
    reviewCount: 892,
    preparationTime: 5,
    calories: 420,
    ingredients: ["Cream Cheese", "Sugar", "Eggs", "Berry Compote"],
    allergens: ["Dairy", "Egg", "Gluten"],
  },
  {
    id: "dessert-brownie",
    vendorId: "vendor-sweet-treats",
    name: "Fudge Brownie Sundae",
    description: "Warm brownie, vanilla ice cream, hot fudge, whipped cream",
    images: [
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&h=600&fit=crop",
    ],
    price: 9.99,
    category: "desserts",
    cuisine: "American",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 634,
    preparationTime: 8,
    calories: 680,
    ingredients: ["Brownie", "Ice Cream", "Hot Fudge", "Whipped Cream"],
    allergens: ["Gluten", "Dairy", "Egg", "Soy"],
  },
  {
    id: "bbq-ribs",
    vendorId: "vendor-bbq-shack",
    name: "BBQ Ribs (Half Rack)",
    description: "Slow-smoked pork ribs with signature BBQ sauce",
    images: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop",
    ],
    price: 22.99,
    category: "bbq",
    cuisine: "American",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 456,
    preparationTime: 30,
    calories: 890,
    ingredients: ["Pork Ribs", "BBQ Sauce", "Spices"],
    allergens: ["None"],
    customizations: [
      {
        id: "sauce",
        name: "BBQ Sauce",
        type: "single",
        required: false,
        options: [
          { id: "original", name: "Original", price: 0 },
          { id: "spicy", name: "Spicy", price: 0 },
          { id: "sweet", name: "Sweet", price: 0 },
        ],
      },
    ],
  },
  {
    id: "breakfast-pancakes",
    vendorId: "vendor-breakfast-club",
    name: "Stack of Pancakes",
    description: "Three fluffy pancakes with butter and maple syrup",
    images: [
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop",
    ],
    price: 8.99,
    category: "breakfast",
    cuisine: "American",
    isAvailable: true,
    rating: 4.7,
    reviewCount: 789,
    preparationTime: 12,
    calories: 520,
    ingredients: ["Pancake Mix", "Butter", "Maple Syrup"],
    allergens: ["Gluten", "Egg", "Dairy"],
    customizations: [
      {
        id: "toppings",
        name: "Add Toppings",
        type: "multiple",
        required: false,
        options: [
          { id: "blueberries", name: "Blueberries", price: 2 },
          { id: "strawberries", name: "Strawberries", price: 2 },
          { id: "bananas", name: "Bananas", price: 1.5 },
          { id: "chocolate-chips", name: "Chocolate Chips", price: 2.5 },
        ],
      },
    ],
  },
  {
    id: "wings-classic",
    vendorId: "vendor-wing-zone",
    name: "Classic Wings (10 pcs)",
    description: "Crispy chicken wings tossed in buffalo sauce",
    images: [
      "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&h=600&fit=crop",
    ],
    price: 14.99,
    category: "wings",
    cuisine: "American",
    isAvailable: true,
    rating: 4.6,
    reviewCount: 1023,
    preparationTime: 20,
    calories: 780,
    ingredients: ["Chicken Wings", "Buffalo Sauce"],
    allergens: ["None"],
    customizations: [
      {
        id: "heat",
        name: "Heat Level",
        type: "single",
        required: true,
        options: [
          { id: "mild", name: "Mild", price: 0 },
          { id: "medium", name: "Medium", price: 0 },
          { id: "hot", name: "Hot", price: 0 },
          { id: "extra-hot", name: "Extra Hot", price: 0 },
        ],
      },
    ],
  },
  {
    id: "sub-meatball",
    vendorId: "vendor-sub-way",
    name: "Meatball Sub",
    description: "Meatballs, marinara sauce, mozzarella on Italian bread",
    images: [
      "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&h=600&fit=crop",
    ],
    price: 9.99,
    category: "sandwiches",
    cuisine: "Italian",
    isAvailable: true,
    rating: 4.5,
    reviewCount: 456,
    preparationTime: 10,
    calories: 580,
    ingredients: ["Meatballs", "Marinara", "Mozzarella", "Italian Bread"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "pasta-carbonara",
    vendorId: "vendor-pasta-house",
    name: "Spaghetti Carbonara",
    description:
      "Classic Italian pasta with bacon, egg, parmesan, black pepper",
    images: [
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop",
    ],
    price: 15.99,
    category: "italian",
    cuisine: "Italian",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 678,
    preparationTime: 18,
    calories: 680,
    ingredients: ["Spaghetti", "Bacon", "Egg", "Parmesan", "Black Pepper"],
    allergens: ["Gluten", "Egg", "Dairy", "Pork"],
  },
  {
    id: "seafood-lobster",
    vendorId: "vendor-seafood-lovers",
    name: "Lobster Roll",
    description: "Fresh lobster meat on buttered brioche roll",
    images: [
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=600&fit=crop",
    ],
    price: 24.99,
    category: "seafood",
    cuisine: "American",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 234,
    preparationTime: 15,
    calories: 520,
    ingredients: ["Lobster", "Butter", "Brioche Roll", "Lemon"],
    allergens: ["Shellfish", "Gluten", "Dairy"],
  },
];
